name: "Compile on Ubuntu with emscripten"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@v9
    - name: build
      run: |
        emcmake cmake -E make_directory build
        cd build
        emcmake cmake -DUSE_INTERNAL_PCRE2=on ..
        emmake make -j2
    - name: list build dir
      run: ls -hal
      working-directory: build
